// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockQueueService is an autogenerated mock type for the QueueService type
type MockQueueService struct {
	mock.Mock
}

// ConsumeMessages provides a mock function with given fields: ctx
func (_m *MockQueueService) ConsumeMessages(ctx context.Context) {
	_m.Called(ctx)
}

// GetQueueName provides a mock function with given fields:
func (_m *MockQueueService) GetQueueName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetQueueName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// UpdateQueueUrl provides a mock function with given fields: ctx
func (_m *MockQueueService) UpdateQueueUrl(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateQueueUrl")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockQueueService creates a new instance of MockQueueService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueueService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueueService {
	mock := &MockQueueService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
