apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-production-management
  namespace: ns-productions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-production-management
  template:
    metadata:
      labels:
        app: ms-production-management
    spec:
      serviceAccountName: sa-productions
      containers:
        - name: ms-production-management
          image: jsfelipearaujo/ms-production-management:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 200Mi
              cpu: 100m
            requests:
              memory: 100Mi
              cpu: 100m
          envFrom:
            - configMapRef:
                name: ms-production-management-config
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: database-url
                  key: url
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "aws-secrets"
