apiVersion: v1
kind: Service
metadata:
  name: ms-production-management
  namespace: ns-productions
  labels:
    app: ms-production-management
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: ms-production-management