// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import (
	context "context"

	order_entity "github.com/jfelipearaujo-org/ms-production-management/internal/entity/order_entity"
	mock "github.com/stretchr/testify/mock"
)

// MockGetOrderProductionByStateService is an autogenerated mock type for the GetOrderProductionByStateService type
type MockGetOrderProductionByStateService[T interface{}] struct {
	mock.Mock
}

// Handle provides a mock function with given fields: ctx, request
func (_m *MockGetOrderProductionByStateService[T]) Handle(ctx context.Context, request T) ([]order_entity.Order, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 []order_entity.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, T) ([]order_entity.Order, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, T) []order_entity.Order); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]order_entity.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, T) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockGetOrderProductionByStateService creates a new instance of MockGetOrderProductionByStateService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetOrderProductionByStateService[T interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetOrderProductionByStateService[T] {
	mock := &MockGetOrderProductionByStateService[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
